let tronTestNetNile = "https://nile.trongrid.io/"
let ethereumTestNetNile = "https://1rpc.io/sepolia"
let bnbSmartChain = "https://data-seed-prebsc-1-s1.bnbchain.org:8545"
let bnbBeaconChain = "https://data-seed-pre-0-s1.bnbchain.org:443"
let bitcoinChain = "https://blockstream.info/api/address/{address}/txs"
let polygonChain = "https://rpc-mumbai.polygon.technology/"